### YAML Schema for resource deployments using mini-tf ###

parameters:
  - name: environment
    type: string
    value: 'dev'

resources:
  - name: config_file_{{ .parameters.environment }}
    displayName: JSON example
    type: file
    properties:
      extension: .json
      location: '{{ .resources.config_folder.outputs.path }}'
    outputs:
      path: properties.location
    dependsOn: [config_folder]
    
  - name: config_folder
    displayName: Config directory
    type: folder
    properties:
      location: tests/etc/mini-tf
    outputs:
      path: properties.location
