### YAML Schema for resource deployments using mini-tf ###

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - 'dev'
      - 'stage'
      - 'prod'

variables:
  defaultPermissions: 'read'

resources:
  - name: config_folder
    displayName: Config directory
    type: folder
    properties:
      location: /etc/mini-tf
    outputs:
      path: properties.location

  - name: config_file
    displayName: JSON example
    type: file
    properties:
      extension: .json
      location: '{{ .resources.config_folder.outputs.path }}'
    outputs:
      path: properties.location
    dependsOn: [config_folder]
