### YAML Schema for resource deployments using mini-tf ###

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - 'dev'
      - 'stage'
      - 'prod'

variables:
  defaultPermissions: 'read'

resources:
  - resource: example
    displayName: JSON example
    type: file
    properties:
      extension: .json
      location: /usr/bin

  - resource: example2
    displayName: Go example
    type: file
    properties:
      extension: .go
      location: /